[2024-05-16T06:27:26.206+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.analyze_data manual__2024-05-16T06:26:53.782417+00:00 [queued]>
[2024-05-16T06:27:26.216+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.analyze_data manual__2024-05-16T06:26:53.782417+00:00 [queued]>
[2024-05-16T06:27:26.217+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-05-16T06:27:26.239+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): analyze_data> on 2024-05-16 06:26:53.782417+00:00
[2024-05-16T06:27:26.249+0000] {standard_task_runner.py:60} INFO - Started process 1188 to run task
[2024-05-16T06:27:26.252+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline', 'analyze_data', 'manual__2024-05-16T06:26:53.782417+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmplnmhktwa']
[2024-05-16T06:27:26.254+0000] {standard_task_runner.py:88} INFO - Job 38: Subtask analyze_data
[2024-05-16T06:27:26.324+0000] {task_command.py:423} INFO - Running <TaskInstance: data_pipeline.analyze_data manual__2024-05-16T06:26:53.782417+00:00 [running]> on host 07f30c3fd53d
[2024-05-16T06:27:26.423+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='analyze_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-16T06:26:53.782417+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-16T06:26:53.782417+00:00'
[2024-05-16T06:27:26.556+0000] {logging_mixin.py:188} INFO - Summary Statistics:
count    1.572000e+03
mean     1.522368e+06
std      1.916134e+06
min      5.500000e+04
25%      7.415000e+05
50%      1.055500e+06
75%      1.622000e+06
max      2.400000e+07
Name: sold_price, dtype: float64
[2024-05-16T06:27:26.557+0000] {logging_mixin.py:188} INFO - Min Price: 55000
[2024-05-16T06:27:26.558+0000] {logging_mixin.py:188} INFO - Max Price: 24000000
[2024-05-16T06:27:26.559+0000] {logging_mixin.py:188} INFO - Median Price: 1055500.0
[2024-05-16T06:27:26.559+0000] {logging_mixin.py:188} INFO - Mean Price: 1522368.3804071248
[2024-05-16T06:27:26.560+0000] {logging_mixin.py:188} INFO - Standard Deviation: 1916134.379685709
[2024-05-16T06:27:26.569+0000] {xcom.py:664} ERROR - Object of type Series is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2024-05-16T06:27:26.572+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/json.py", line 91, in default
    return serialize(o)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/serialization/serde.py", line 189, in serialize
    raise TypeError(f"cannot serialize object of type {cls}")
TypeError: cannot serialize object of type <class 'pandas.core.series.Series'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/airflow/dags/pipeline.py", line 100, in analyze_data
    ti.xcom_push(key='analysis_summary', value=summary)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3013, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/xcom.py", line 247, in set
    value = cls.serialize_value(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/xcom.py", line 662, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/json.py", line 104, in encode
    return super().encode(o)
  File "/usr/local/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/json.py", line 93, in default
    return super().default(o)
  File "/usr/local/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Series is not JSON serializable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/pipeline.py", line 103, in analyze_data
    print("Error in analyze_data:", exc_info=True)
TypeError: 'exc_info' is an invalid keyword argument for print()
[2024-05-16T06:27:26.595+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=data_pipeline, task_id=analyze_data, execution_date=20240516T062653, start_date=20240516T062726, end_date=20240516T062726
[2024-05-16T06:27:26.611+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 38 for task analyze_data ('exc_info' is an invalid keyword argument for print(); 1188)
[2024-05-16T06:27:26.629+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-16T06:27:26.652+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
